### ISSUE TITLE
Create  a "New member setup readme" 

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#123]
Should be at root, separate readme from `README. md`. Should walk new members through a few tutorials to help them get up and running. First tutorial should be git, later ones should cover useful aspects of ROS (and maybe Gazebo)? @raadkhan, what was the git tutorial you used?

**Comment by raadkhan** [comment]
@garethellis https://try.github.io/levels/1/challenges/1
This one is also kind of nice using GUI:
https://guides.github.com/activities/hello-world/

**Comment by garethellis0** [comment]
@RobynCastro @raadkhan - could you guys post some suggestions here for stuff that you found useful? 

@raadkhan - I'm assigning this to you because you went through the onboarding process the most recently, and so are most likely to understand any issues that new members may face. Try and get this done before orientation sept 23 if possible. Let me know if you have questions

**Comment by garethellis0** [comment]
Some suggestions (Feel free to just edit this comment to add more):
- Rarely will github issues contain all the information that you need to resolve them. Don't be afraid to ask for help, clarification, or just more information.

**Comment by raadkhan** [comment]
@garethellis0 is it possible to get access to the software challenge page on the snowbots website (looks like the website is being updated and that page is not there now)?

**Comment by garethellis0** [comment]
Just to confirm, the top taskbar is broken on mobile on the website? If so, could you open an issue on our website repo https://github.com/UBC-Snowbots/UBC-Snowbots.github.io/issues  to see if @SimonJinaphant can fix this?   Thanks for noticing that, good catch!

**Comment by raadkhan** [comment]
done by @SimonJinaphant
