### ISSUE TITLE
Create IPM filter for stereo camera

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#124]
- We have a shiny new Zed stereo camera that we should probably put to use. 
- Create an IPM filter to get the ground plane as the Zed sees it, and convert it in to a 2D, bird's-eye image. 
- will be very different from our current IPM filter, as since we have depth we can calculate the angles on the fly.

**Comment by ValRat** [comment]
Deprecated in favor of #225, #226, #227
