### ISSUE TITLE
Zed submodule not being blacklisted in CLion

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#127]
- Currently, I believe that CLion is using the old `catkin_make` command or equivalent to build. 
- We have migrated to using `catkin_tools`, with the `catkin build` command, as it allows us to blacklist packages that we might not be able to build from being built along with everything else
- **We need to**: Figure out how to make CLion use the `catkin build` command

**Current Workaround**: create an empty file called `CATKIN_IGNORE` in the `src/zed-ros-wrapper`,  or just don't clone with submodules.

**Comment by garethellis0** [comment]
@ValRat - can you confirm that switching over to the old build tools has fixed this?

**Comment by garethellis0** [comment]
@ValRat - please see above comment

**Comment by garethellis0** [comment]
@ValRat - :point_up: :point_up: :point_up:

**Comment by ValRat** [comment]
Will look at tonight

**Comment by garethellis0** [comment]
This isn't ideal, but I'm OK with it for now, mostly because I don't see any way to a better solution.
