### ISSUE TITLE
Rewrite ros_arduino_bridge firmware to remove all motor controller stuff

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#133]
Currently, the firmware for `ros_arduino_bridge` has a bunch of stuff for controlling motors that we don't need. It should be rewritten so all motor controller stuff is removed, and added to the firmware folder.

**Comment by Dulluhan** [comment]
What piece of code is this, I'll take the Arduino projects if no one is doing them

**Comment by garethellis0** [comment]
We're maintaining our own fork here: https://github.com/UBC-Snowbots/ros_arduino_bridge

**Comment by Dulluhan** [comment]
What is this for

**Comment by garethellis0** [comment]
we're using it for:
- encoder firmware
- encoder driver
- translating what  we get from the encoders into an [odom message](http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html)
