### ISSUE TITLE
Add Branch Naming Conventions to main README

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#153]
Currently, branches are just named willy-nilly, which results in non-descriptive branch names and people trying to use the same branch for different things (or accidentally reusing old branches). To avoid this, we should have some sort of naming convention.

One possible convention: `gareth/my-branch-name` (`name/branch-name-with-dashes-for-spaces`)

**Comment by ValRat** [comment]
A non issue with our new forking workflow.
