### ISSUE TITLE
Change the RosVision class name

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#156]
Currently, our vision filtering and IPM filtering node is called `ros_vision` with a class name of `RosVision`. This could probably have a better name, like `vision_processing` and `VisionProcessing`.

**What needs to be done:**
- in `src/vision/ros_vision.cpp` rename the node from `ros_vision` to something better
- change the `RosVision` class name to something better (should follow the node name)
- change all relevant file names.
- test changes by running them in gazebo, or on the robot. This is **really** important, as this is an older portion of the codebase, and so is not unit tested

**Comment by ValRat** [comment]
RosVision is no more, closed with Robyn's amazing changes.
