### ISSUE TITLE
Create a Gazebo world for the IGVC basic course 

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#169]
- We should re-create the entire basic IGVC course as a gazebo world for testing. 
- We should create a version with smooth lines, and another with more roughed up lines
- **Note:** We could add the `Beginner` tag to this if the initial setup is done (ie required files created and somewhat filled in), at which point we would just have to show the person working on it how to add cones and setup textures.
### References 
![image](https://cloud.githubusercontent.com/assets/9075711/25311508/b2453128-27b7-11e7-82cf-f4f54ca84a8f.png)
![image](https://cloud.githubusercontent.com/assets/9075711/25311522/0ccdd262-27b8-11e7-8f95-2362ca6624c4.png)
![image](https://cloud.githubusercontent.com/assets/9075711/25311528/1b07975a-27b8-11e7-84e7-12553b568c1a.png)

**Comment by ValRat** [comment]
MORE REFERENCES:
http://www.igvc.org/spec2vid2.mp4
