### ISSUE TITLE
Include arduino libraries for firmware team

### ISSUE THREAD

**Issue by Dulluhan** [UBC-Snowbots/Snowflake#177]
include firmware library that installs and sets up path for firmware libraries /arduino/lib

**Comment by garethellis0** [comment]
Just saw this while going through issues, I'm a little confused what we're trying to do here?

**Comment by Dulluhan** [comment]
Just saw the comment here, off the top of my head, I think there were some custom libraries used in previous year's arduino code, things didn't build for some people.

**Comment by garethellis0** [comment]
OK, I've double checked with @ValRat and we don't recall which libraries are being referred to here, so I'm closing this.
