### ISSUE TITLE
sb_utils handling templated functions

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/Snowflake#180]
`sb_utils` contains the function `SB_doTransform` which then calls another template function `tf2::doTransform()`. The issue is the calling class of `SB_doTransform` must link to the proper implementation of `tf2::doTransform()` for the proper datatype (i.e. For `sensor_msgs::Pointcloud2` calling class must have `#include <tf2_sensor_msgs/tf2_sensor_msgs.h>`).

We should probably link all of the common `tf2::doTransform()` implementations to `sb_utils` to reduce overhead of the calling classes making it easy and everything should just work (tm).

Note:
Custom datatypes can also leverage `tf2::doTransform()` by implementing it. See [link](http://wiki.ros.org/tf2/Tutorials/Transforming%20your%20own%20datatypes).

**Comment by garethellis0** [comment]
`SB_doTransform` was removed, as it was *not* the right way to use the ROS TF tree. Closing.

**Comment by garethellis0** [comment]
Whoops, I thought it had been removed, but looks like not. @ValRat, what are your thoughts on keeping it around?
