### ISSUE TITLE
Create a series of filters to process Zed (Pointcloud) data

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/Snowflake#215]
The Zed stereo camera gives us pointcloud data to work with. 
A good first step to use this data would be to create a series of [nodelets](http://wiki.ros.org/nodelet) (Ref: [1](https://answers.ros.org/question/230972/what-is-a-nodelet/) [2](http://wiki.ros.org/nodelet/Tutorials)) that can be combined to transform the pointcloud in various ways.
Some suggestions include:
- Birds Eye View (IPM-esque) See #124
- Filter on colour
- Filter on height

 Also would be super handy if they were [dynamically reconfigurable](http://wiki.ros.org/dynamic_reconfigure).

**Comment by garethellis0** [comment]
Closing in favour of #225 and #226
