### ISSUE TITLE
Create a "ROS Cheatsheet"

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#218]
- Should detail useful things that people should know to get up and running with ROS. 
- Doesn't have to be limited to one page, but try and keep it pretty succinct

**Comment by raadkhan** [comment]
refer/update www.clearpathrobotics.com/ros-cheat-sheet

**Comment by garethellis0** [comment]
Hmm. @ValRat @RobynCastro, do you guys have any thoughts as to whether or not this is worth pursuing further? Or is the document that Raad linked above sufficient?

**Comment by ValRat** [comment]
It's good, but needs small updates here and there i.e. hydro to kinetic. Not super worried about it, can probably close this issue.
