### ISSUE TITLE
Create Node to filter Pointcloud based on height from ground level

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#225]
We would like to be able to filter points the in the pointcloud coming from the Zed based on their height from the ground. The general structure would be:
- take in `sensor_msgs/Pointcloud`
- using the [transform tree](http://wiki.ros.org/tf), translate the pointcloud from it's frame of reference (relative to the Zed) to the frame of reference of the robot
- Filter the points based on their height (their z value in the robots frame of reference)
- publish the filtered cloud

**Notes**
- ideally this node will be [dynamically reconfigurable](http://wiki.ros.org/dynamic_reconfigure) so that we can change height range

**Comment by garethellis0** [comment]
Interesting note that @ValRat made over on #226:
"After rolling out my own filter node I found out that: 
`pcl_ros` provides nodelets for various [filters](http://wiki.ros.org/pcl_ros/Tutorials/filters
)."

**Comment by garethellis0** [comment]
Interesting note that @ValRat made over on #226:
"After rolling out my own filter node I found out that: 
`pcl_ros` provides nodelets for various [filters](http://wiki.ros.org/pcl_ros/Tutorials/filters
)."

**Comment by garethellis0** [comment]
@ValRat - is this resolved now?

**Comment by ValRat** [comment]
Yep
