### ISSUE TITLE
Create a Node to filter Pointcloud based on HSV

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#226]
We would like to be able to filter colored point from the Zed stereo camera and filter it based on Hue, Saturation, and Value (HSV). The general structure here would be:
- take in the colored pointcloud
- filter all the points based on HSV
- publish the filtered pointcloud

**Notes**
- we tried HSV filtering with [pcl](http://wiki.ros.org/pcl) before, but found it to be *absurdly* slow (it involves converting a ROS pointcloud to a PCL pointcloud, filtering it, then converting it back). So we'll likely have to role our own here
- ideally this node will be [dynamically reconfigurable](http://wiki.ros.org/dynamic_reconfigure) so that we can change the H, S, and V ranges while the node is running and see the result.

**Comment by ValRat** [comment]
Working Notes:

After rolling out my own filter node I found out that: 
`pcl_ros` provides nodelets for various [filters](http://wiki.ros.org/pcl_ros/Tutorials/filters
).

Going to try leveraging that instead...
