### ISSUE TITLE
Create or Find a Pathfinding Node

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#232]
We could either use a pre-rolled node for this, or just role our own using something like A* with a simple heuristic. General structure would be:
- take in a `nav_msgs/OccupancyGrid` and a goal (a `geometry_msgs/Point`)
- get our current position from the `tf` tree
- calculate a path from our current position to the goal
- broadcast the path as a `nav_msgs/Path` message

**Comment by garethellis0** [comment]
As an update to this:
- the end goal may not be on the map (as we want to maintain the smallest occupancy grid possible), and so the final solution should account for this

**Comment by garethellis0** [comment]
- the obstacle manager (the node that generates the occupancy grids) will have the option to inflate obstacles, so that should hopefully simplify things a bit (the path doesn't need to account for the width of the robot if obstacles are inflated enough)

**Comment by raadkhan** [comment]
Resolved
