### ISSUE TITLE
Create a Node to Convert a Path to a Twist

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#233]
We would like a node to convert a given path into a Twist message to send to the robot. The general structure would be:
- take in a path
- compute a twist message from the path
- broadcast the calculated twist message

![image](https://user-images.githubusercontent.com/9075711/31260924-22cd0ca6-aa06-11e7-8ae4-07d28475754a.png)

**Comment by garethellis0** [comment]
@WilliamGu98 - is this resolved now?

**Comment by WilliamGu98** [comment]
Yeah I just merged it yesterday

**Comment by garethellis0** [comment]
Great! Just a note for the future, you can automatically close issues with a pull request, see here for details: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by WilliamGu98** [comment]
Alright thanks, I'll take note of that
