### ISSUE TITLE
.rosinstall doesn't seem to 'install' packages as we think it does

### ISSUE THREAD

**Issue by ValRat** [UBC-Snowbots/Snowflake#304]
Looks like `rosinstall` is more of a scv agnostic source file grabber. We can keep using it, but proposing that we put the repositories pulled under `/src/external_pkgs` so that all gets built locally using `catkin_make`.

**Comment by garethellis0** [comment]
I really like this idea! @Dulluhan - you've got the most experience with this stuff currently, what do you think?

**Comment by Dulluhan** [comment]
Unfortunately it seems like the only solution right now. This also means we will have to look ahead and figure out how we want to install the dependencies for certain packages. Maybe changing the order of how we run the `install_depdendencies` script and run `rosinstall` before `rosdep update`?

**Comment by ValRat** [comment]
To clean up the discussion, `wstool` is the next iteration of `rosinstall` and the changes in the code have been made to reflect that.

**Comment by Dulluhan** [comment]
I was under the impression that `rosinstall` replaced `wstool` :open_mouth:
