### ISSUE TITLE
Create a Search Algorithm to Find Marker

### ISSUE THREAD

**Issue by RobynCastro** [UBC-Snowbots/Snowflake#331]
After the robot reaches the GPS coordinates in the autonomous traversal task, it needs to find the goal marker. The marker will be a tennis ball, and may not be near the GPS coordinates. Some kind of search algorithm needs to be implemented to find and stop at the tennis marker.

**Comment by mingyokim** [comment]
To be clear, this issue should only be responsible for "sweeping" around the GPS coordinates, right? #332 is the one that actually detects the marker/tennis ball?
