### ISSUE TITLE
Create A System to Detect Markers

### ISSUE THREAD

**Issue by RobynCastro** [UBC-Snowbots/Snowflake#332]
We need to be able to recognize that we have found the marker. Markers will be a standard tennis ball elevated 10 - 50 cm off the ground.

**Comment by mingyokim** [comment]
Proposal: *Reuse our current software as much as possible!*

Input: from realsense (or any other pointclouds)

1. Perform height filter (remove all points below a certain height)
2. Perform HSV filter (remove all points that are not green?)
3. Perform DBSCAN (find the cluster of points that belong to the tennis ball)
4. (NEW, but pretty trivial) Calculate the center point (x,y,z) of the tennis ball
