### ISSUE TITLE
Create a Reactive System for Obstacle Avoidance

### ISSUE THREAD

**Issue by RobynCastro** [UBC-Snowbots/Snowflake#347]
On the course there will be various slopes or objects (rocks, hills, etc.) that the robot cannot pass through. If there is one of these in the robot's line of sight (lidar and/or stereo camera), it should attempt to avoid it.

**Comment by garethellis0** [comment]
The system should move towards the destination GPS waypoint unless there is an obstacle in the way (as detected by the lidar and/or stereo camera) in which case it should avoid the obstacle.
