### ISSUE TITLE
Revert Changes from #366

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#360]
Unfortunately `librealsense` was updated to `2.16.2`, and the associated ROS packages were not. The ROS packages will be released, but until then we've had to peg the `librealsense` version to `2.16.1`. 

Once https://github.com/intel-ros/realsense/issues/502 is resolved, we should revert the changes added in #359.

**Comment by RobynCastro** [comment]
Also need https://github.com/intel-ros/realsense/issues/513 to be resolved before we can revert the changes.

**Comment by garethellis0** [comment]
Re-opened because of the issue robyn mentioned above.

**Comment by ihsan314** [comment]
Closing because the setup script installs `librealsense` properly.
