### ISSUE TITLE
Detect when we have observed a QR code or a particular marker type

### ISSUE THREAD

**Issue by ihsan314** [UBC-Snowbots/Snowflake#412]
We have two Intel Realsense cameras publishing to the topics `/cam1/color/image_raw/compressed` and `/cam2/color/image_raw/compressed`.

During competition, these cameras may potentially be pointed towards markers from a dictionary of 50 4x4 ArUco markers or QR codes with a status message.

We need to create a node or two that will subscribe to the camera feeds, scan for a marker/QR code, and report back with the marker numbers or the contents of the QR codes found.

OpenCV is known to [cooperate with ROS](https://wiki.ros.org/cv_bridge/Tutorials) and can handle the [detection of ArUco markers](https://docs.opencv.org/4.x/d5/dae/tutorial_aruco_detection.html) as well as the [detection of QR codes](https://docs.opencv.org/4.x/de/dc3/classcv_1_1QRCodeDetector.html). We've also successfully used OpenCV before in this repo, in the [`sb_vision`](https://github.com/UBC-Snowbots/Snowflake/tree/master/src/sb_vision) package. So this task can likely be accomplished with OpenCV.

OpenCV also prepared sample [ArUco marker detection code](https://github.com/opencv/opencv_contrib/blob/f6a39c5d01a7b2d2bb223a2a67beb9736fce7d93/modules/aruco/samples/detect_markers.cpp) and [QR detection code](https://github.com/opencv/opencv/blob/17234f82d025e3bbfbf611089637e5aa2038e7b8/samples/cpp/qrcode.cpp).

**Comment by Roozki** [comment]
looking into scanning codes with OpenCV, it has a built in package that scans aruco codes so this issue shouldn't be too difficult. However we should consider ways of making sure the cameras are pointing at the codes.
I'm thinking:
1. proximity to the GPS waypoint will trigger the scanning node
2. then the node checks if there is a code and attempts to scan
3. if no codes are found, the driveterrain rotates the camera
4. repeat 2-3, but make sure to "time out" if no codes are found

**Comment by ihsan314** [comment]
That's a lot smarter than continuously scanning, which was what I was initially thinking.

1 can be accomplished by publishing to a topic.

2 can be done by looking at the most recently received frames from either camera and checking if a marker or code has been found

3 can be done by spinning the rover slowly.
