### ISSUE TITLE
Mapping System

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#52]
**This issue will likely be split off into multiple issues later on, as we decide on how to split up projects**

- Full mapping with the `grid_map` library
- (Tentatively) separate layers for vision and lidar
- Possibly discrete obstacle detection for cones since we know how big they are? Most of the code is in the `decision->LidarObstacle` class, and the rest is either trivial, or needs to be moved from the `LidarDecision` class to the `LidarObstacle` class

**Comment by ValRat** [comment]
Closing and making new issue for mapping based on system fleshed out on September 2018.

**Comment by garethellis0** [comment]
**Note:** new mapping system is #231
