### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#53]
- full localisation integrating IMU, Lidar, Encoders
- will likely be implemented with some sort of Kalman Filter (either extended or unscented) though research into this still needs to be done
- After some basic research, it looks like there are several ROS packages that do what we need, so this is likely a 1 person job

**Comment by garethellis0** [comment]
@lkhume This is where I'd like to keep discussion of the new localization system (mostly for documentation and organization purposes). If you've anything you want me to see, just add @garethellis0 to it, and i'll get notified (some goes for anyone else, like val)

**Comment by ValRat** [comment]
Obsolete, make a new issue for this.

**Comment by garethellis0** [comment]
*Note:* Closed in favor of #230
